### PR TITLE
Show message & play sfx when a secret is found

### PR DESCRIPTION
**Pull request by ColleagueRiley**
Since most of my old code was removed, I decided to make a new fork.

### CODE REVIEW

**Comment by ColleagueRiley** [comment]
Oops 💀

**Comment by Daivuk** [comment]
Amazing, must simple :)

**Comment by Daivuk** [comment]
Do you mind squashing your commits into 1?
image

**Comment by ColleagueRiley** [comment]
Is there a way to do that without making a new fork?

**Comment by Daivuk** [comment]
> Is there a way to do that without making a new fork?

Yes.
`git rebase -i HEAD~3`
leave first commit alone, 2 bellow remove the hash and put `f` in front, for "squash up".
You will have to force push.

If you dont really know how to do this, dont worry then. Leave it as is.

**Pull request merged**
